/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.Main;
import objects.LoginSystem;

/**
 *
 * @author Michael Tomlinson
 */
public class MainGUI extends javax.swing.JFrame {
public String username, Password;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        StartPage1.setVisible(true);
        StartPage1.enable();
        
        LoginPage2.setVisible(false);
        LoginPage2.disable();
        
        AdminVerification2.setVisible(false);
        AdminVerification2.disable();
        
        AddUserPage3.setVisible(false);
        AddUserPage3.disable();
        
        OptionSelect3.setVisible(false);
        OptionSelect3.disable();
        
        AddDrive4.setVisible(false);
        AddDrive4.disable();
        
        AddSighting5.setVisible(false);
        AddSighting5.disable();
        
        AnimalDropUpdate();
        
    }
    public String Enter(String Username, String Password){
        this.username = Username;
        this.Password = Password;
        LoginSystem us = new LoginSystem();
        String outcome = us.verifyUser(this.username, this.Password);
        return outcome;
}
        public void AddUser(String Username, String Password){
        this.username = Username;
        this.Password = Password;
        LoginSystem us = new LoginSystem();
        us.addUser(Username, Password);
        }
        
        public void AnimalDropUpdate(){
        Connection c = null;
        Statement s =null;
        ResultSet r = null;
            try {
            c = DriverManager.getConnection("jdbc:derby://localhost:1527/GameDriveSystem", "Michael", "Tomlinson" );
            s = c.createStatement();
            r = s.executeQuery("SELECT * FROM MICHAEL.ANIMALS ORDER BY ANIMALTYPE ASC");
            while(r.next()){
            AnimalDropbox.addItem(r.getString("ANIMALTYPE"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartPage1 = new javax.swing.JPanel();
        WelcomeTitle = new javax.swing.JLabel();
        WelcomeTitle1 = new javax.swing.JLabel();
        WelcomeTitle2 = new javax.swing.JLabel();
        LoginStart = new javax.swing.JButton();
        AddUserStart = new javax.swing.JButton();
        HelpStart = new javax.swing.JButton();
        LogoStart = new javax.swing.JLabel();
        LoginPage2 = new javax.swing.JPanel();
        LoginTitle = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        InputUsername = new javax.swing.JTextField();
        LoginContinue = new javax.swing.JButton();
        LoginHelp = new javax.swing.JButton();
        InputPassword = new javax.swing.JPasswordField();
        Logo = new javax.swing.JLabel();
        AdminVerification2 = new javax.swing.JPanel();
        Logo2 = new javax.swing.JLabel();
        LoginTitle1 = new javax.swing.JLabel();
        UsernameLabel2 = new javax.swing.JLabel();
        PasswordLabel2 = new javax.swing.JLabel();
        InputUsername2 = new javax.swing.JTextField();
        LoginContinue1 = new javax.swing.JButton();
        LoginHelp1 = new javax.swing.JButton();
        InputPassword2 = new javax.swing.JPasswordField();
        AddUserPage3 = new javax.swing.JPanel();
        AddUserTitle = new javax.swing.JLabel();
        UsernameLabel1 = new javax.swing.JLabel();
        PasswordLabel1 = new javax.swing.JLabel();
        InputUsername1 = new javax.swing.JTextField();
        AddUserContinue = new javax.swing.JButton();
        AddUserHelp = new javax.swing.JButton();
        InputPassword1 = new javax.swing.JPasswordField();
        Logo1 = new javax.swing.JLabel();
        OptionSelect3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        AddDrive4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        AddSighting5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AnimalDropbox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));

        StartPage1.setBackground(new java.awt.Color(0, 255, 204));
        StartPage1.setPreferredSize(new java.awt.Dimension(800, 450));

        WelcomeTitle.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        WelcomeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeTitle.setText("Welcome");

        WelcomeTitle1.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        WelcomeTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeTitle1.setText("to the");

        WelcomeTitle2.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        WelcomeTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeTitle2.setText("Game Drive Recording System");

        LoginStart.setBackground(new java.awt.Color(0, 255, 204));
        LoginStart.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        LoginStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Button.jpg"))); // NOI18N
        LoginStart.setText("Login");
        LoginStart.setBorder(null);
        LoginStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginStartActionPerformed(evt);
            }
        });

        AddUserStart.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        AddUserStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Button.jpg"))); // NOI18N
        AddUserStart.setText("Add User");
        AddUserStart.setBorder(null);
        AddUserStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddUserStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserStartActionPerformed(evt);
            }
        });

        HelpStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Help.jpg"))); // NOI18N
        HelpStart.setBorder(null);
        HelpStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpStartActionPerformed(evt);
            }
        });

        LogoStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Logo.jpg"))); // NOI18N

        javax.swing.GroupLayout StartPage1Layout = new javax.swing.GroupLayout(StartPage1);
        StartPage1.setLayout(StartPage1Layout);
        StartPage1Layout.setHorizontalGroup(
            StartPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPage1Layout.createSequentialGroup()
                .addGroup(StartPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WelcomeTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addComponent(WelcomeTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(StartPage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StartPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartPage1Layout.createSequentialGroup()
                        .addComponent(HelpStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoStart))
                    .addGroup(StartPage1Layout.createSequentialGroup()
                        .addGroup(StartPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StartPage1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(LoginStart)
                                .addGap(18, 18, 18)
                                .addComponent(AddUserStart, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(WelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        StartPage1Layout.setVerticalGroup(
            StartPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPage1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(WelcomeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WelcomeTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WelcomeTitle2)
                .addGap(66, 66, 66)
                .addGroup(StartPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddUserStart, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StartPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartPage1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LogoStart))
                    .addComponent(HelpStart, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        LoginPage2.setBackground(new java.awt.Color(0, 255, 204));
        LoginPage2.setPreferredSize(new java.awt.Dimension(800, 450));

        LoginTitle.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        LoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LoginTitle.setText("Login:");

        UsernameLabel.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        UsernameLabel.setText("Username:");

        PasswordLabel.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        PasswordLabel.setText("Password:");

        InputUsername.setBackground(new java.awt.Color(0, 255, 204));
        InputUsername.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        InputUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        LoginContinue.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        LoginContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Button.jpg"))); // NOI18N
        LoginContinue.setText("Continue");
        LoginContinue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginContinueActionPerformed(evt);
            }
        });

        LoginHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Help.jpg"))); // NOI18N

        InputPassword.setBackground(new java.awt.Color(0, 255, 204));
        InputPassword.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        InputPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Logo.jpg"))); // NOI18N

        javax.swing.GroupLayout LoginPage2Layout = new javax.swing.GroupLayout(LoginPage2);
        LoginPage2.setLayout(LoginPage2Layout);
        LoginPage2Layout.setHorizontalGroup(
            LoginPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPage2Layout.createSequentialGroup()
                .addGroup(LoginPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPage2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(LoginHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(369, 369, 369)
                        .addComponent(LoginContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPage2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(LoginPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LoginPage2Layout.createSequentialGroup()
                                .addComponent(LoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Logo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPage2Layout.createSequentialGroup()
                                .addGroup(LoginPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(LoginPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InputUsername)
                                    .addComponent(InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        LoginPage2Layout.setVerticalGroup(
            LoginPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPage2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LoginPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logo))
                .addGroup(LoginPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(LoginPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPage2Layout.createSequentialGroup()
                        .addComponent(LoginHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGap(19, 19, 19))
        );

        AdminVerification2.setBackground(new java.awt.Color(0, 255, 204));
        AdminVerification2.setPreferredSize(new java.awt.Dimension(800, 450));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Logo.jpg"))); // NOI18N

        LoginTitle1.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        LoginTitle1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LoginTitle1.setText("Login as Admin:");

        UsernameLabel2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        UsernameLabel2.setText("Username:");

        PasswordLabel2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        PasswordLabel2.setText("Password:");

        InputUsername2.setBackground(new java.awt.Color(0, 255, 204));
        InputUsername2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        InputUsername2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        LoginContinue1.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        LoginContinue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Button.jpg"))); // NOI18N
        LoginContinue1.setText("Continue");
        LoginContinue1.setBorder(null);
        LoginContinue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginContinue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginContinue1ActionPerformed(evt);
            }
        });

        LoginHelp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Help.jpg"))); // NOI18N
        LoginHelp1.setBorder(null);

        InputPassword2.setBackground(new java.awt.Color(0, 255, 204));
        InputPassword2.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        InputPassword2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout AdminVerification2Layout = new javax.swing.GroupLayout(AdminVerification2);
        AdminVerification2.setLayout(AdminVerification2Layout);
        AdminVerification2Layout.setHorizontalGroup(
            AdminVerification2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminVerification2Layout.createSequentialGroup()
                .addGroup(AdminVerification2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminVerification2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(LoginHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(369, 369, 369)
                        .addComponent(LoginContinue1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminVerification2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(AdminVerification2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminVerification2Layout.createSequentialGroup()
                                .addComponent(LoginTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Logo2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminVerification2Layout.createSequentialGroup()
                                .addGroup(AdminVerification2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(UsernameLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PasswordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AdminVerification2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InputUsername2)
                                    .addComponent(InputPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        AdminVerification2Layout.setVerticalGroup(
            AdminVerification2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminVerification2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AdminVerification2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logo2))
                .addGroup(AdminVerification2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminVerification2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(AdminVerification2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginContinue1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminVerification2Layout.createSequentialGroup()
                        .addComponent(LoginHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGap(19, 19, 19))
        );

        AddUserPage3.setBackground(new java.awt.Color(0, 255, 204));
        AddUserPage3.setPreferredSize(new java.awt.Dimension(800, 450));

        AddUserTitle.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        AddUserTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AddUserTitle.setText("Add User:");

        UsernameLabel1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        UsernameLabel1.setText("Username:");

        PasswordLabel1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        PasswordLabel1.setText("Password:");

        InputUsername1.setBackground(new java.awt.Color(0, 255, 204));
        InputUsername1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        InputUsername1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        InputUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputUsername1ActionPerformed(evt);
            }
        });

        AddUserContinue.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        AddUserContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Button.jpg"))); // NOI18N
        AddUserContinue.setText("Continue");
        AddUserContinue.setBorder(null);
        AddUserContinue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddUserContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserContinueActionPerformed(evt);
            }
        });

        AddUserHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Help.jpg"))); // NOI18N
        AddUserHelp.setBorder(null);

        InputPassword1.setBackground(new java.awt.Color(0, 255, 204));
        InputPassword1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        InputPassword1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Logo.jpg"))); // NOI18N

        javax.swing.GroupLayout AddUserPage3Layout = new javax.swing.GroupLayout(AddUserPage3);
        AddUserPage3.setLayout(AddUserPage3Layout);
        AddUserPage3Layout.setHorizontalGroup(
            AddUserPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddUserPage3Layout.createSequentialGroup()
                .addGroup(AddUserPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddUserPage3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(AddUserHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(369, 369, 369)
                        .addComponent(AddUserContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddUserPage3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(AddUserPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AddUserPage3Layout.createSequentialGroup()
                                .addComponent(AddUserTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Logo1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddUserPage3Layout.createSequentialGroup()
                                .addGroup(AddUserPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(UsernameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PasswordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AddUserPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InputUsername1)
                                    .addComponent(InputPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        AddUserPage3Layout.setVerticalGroup(
            AddUserPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddUserPage3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddUserPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddUserTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logo1))
                .addGroup(AddUserPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddUserPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(AddUserPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddUserContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddUserPage3Layout.createSequentialGroup()
                        .addComponent(AddUserHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGap(19, 19, 19))
        );

        OptionSelect3.setBackground(new java.awt.Color(0, 255, 204));
        OptionSelect3.setPreferredSize(new java.awt.Dimension(800, 450));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Logo.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Option:");

        jButton1.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Button.jpg"))); // NOI18N
        jButton1.setText("Add Drive");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("MS Gothic", 1, 22)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Button.jpg"))); // NOI18N
        jButton2.setText("View Previous Drives");
        jButton2.setBorder(null);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Help.jpg"))); // NOI18N
        jButton3.setBorder(null);

        javax.swing.GroupLayout OptionSelect3Layout = new javax.swing.GroupLayout(OptionSelect3);
        OptionSelect3.setLayout(OptionSelect3Layout);
        OptionSelect3Layout.setHorizontalGroup(
            OptionSelect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(OptionSelect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OptionSelect3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(OptionSelect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionSelect3Layout.createSequentialGroup()
                            .addGap(10, 17, Short.MAX_VALUE)
                            .addGroup(OptionSelect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionSelect3Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(88, 88, 88))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionSelect3Layout.createSequentialGroup()
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(610, 610, 610)
                                    .addComponent(jLabel3)
                                    .addGap(34, 34, 34)))))
                    .addContainerGap()))
        );
        OptionSelect3Layout.setVerticalGroup(
            OptionSelect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(OptionSelect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OptionSelect3Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(OptionSelect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(43, 43, 43)
                    .addGroup(OptionSelect3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)))
        );

        AddDrive4.setBackground(new java.awt.Color(0, 255, 204));
        AddDrive4.setPreferredSize(new java.awt.Dimension(800, 450));

        jLabel5.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Drive");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Help.jpg"))); // NOI18N
        jButton5.setBorder(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Logo.jpg"))); // NOI18N

        jButton6.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Button(small).jpg"))); // NOI18N
        jButton6.setText("Continue");
        jButton6.setBorder(null);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel7.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel7.setText("Enter Drive Name:");

        jLabel11.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabel11.setText("Enter Description:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout AddDrive4Layout = new javax.swing.GroupLayout(AddDrive4);
        AddDrive4.setLayout(AddDrive4Layout);
        AddDrive4Layout.setHorizontalGroup(
            AddDrive4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDrive4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddDrive4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddDrive4Layout.createSequentialGroup()
                        .addGroup(AddDrive4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddDrive4Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(447, 447, 447)
                                .addComponent(jButton6))
                            .addGroup(AddDrive4Layout.createSequentialGroup()
                                .addGroup(AddDrive4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddDrive4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AddDrive4Layout.setVerticalGroup(
            AddDrive4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddDrive4Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AddDrive4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddDrive4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AddDrive4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddDrive4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddDrive4Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddDrive4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addGap(9, 9, 9)))
                    .addGroup(AddDrive4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))))
        );

        AddSighting5.setBackground(new java.awt.Color(0, 255, 204));
        AddSighting5.setPreferredSize(new java.awt.Dimension(800, 450));

        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Sighting");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Help.jpg"))); // NOI18N
        jButton4.setBorder(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Logo.jpg"))); // NOI18N

        AnimalDropbox.setBackground(new java.awt.Color(0, 255, 204));
        AnimalDropbox.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        AnimalDropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        AnimalDropbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        AnimalDropbox.setName(""); // NOI18N
        AnimalDropbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalDropboxActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel8.setText("Select Animal:");

        jLabel9.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel9.setText("Quantity:");

        jLabel10.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel10.setText("Description:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jScrollPane1.setViewportView(jTextArea1);

        jSpinner1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jSpinner1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout AddSighting5Layout = new javax.swing.GroupLayout(AddSighting5);
        AddSighting5.setLayout(AddSighting5Layout);
        AddSighting5Layout.setHorizontalGroup(
            AddSighting5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSighting5Layout.createSequentialGroup()
                .addGroup(AddSighting5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSighting5Layout.createSequentialGroup()
                        .addGroup(AddSighting5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddSighting5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AddSighting5Layout.createSequentialGroup()
                                    .addGap(108, 108, 108)
                                    .addComponent(jLabel8))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddSighting5Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabel9)))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddSighting5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AnimalDropbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(jSpinner1))
                        .addGap(0, 184, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddSighting5Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        AddSighting5Layout.setVerticalGroup(
            AddSighting5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSighting5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddSighting5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AnimalDropbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(AddSighting5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSighting5Layout.createSequentialGroup()
                        .addGroup(AddSighting5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1))
                        .addGap(18, 18, 18)
                        .addGroup(AddSighting5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(AddSighting5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StartPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LoginPage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddUserPage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(OptionSelect3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminVerification2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddDrive4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddSighting5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StartPage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LoginPage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddUserPage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(OptionSelect3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AdminVerification2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddDrive4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddSighting5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginStartActionPerformed
        // TODO add your handling code here:
        StartPage1.setVisible(false);
        StartPage1.disable();
        LoginPage2.setVisible(true);
        LoginPage2.enable();
    }//GEN-LAST:event_LoginStartActionPerformed

    private void AddUserStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserStartActionPerformed
        // TODO add your handling code here:
        StartPage1.setVisible(false);
        StartPage1.disable();
        AdminVerification2.setVisible(true);
        AdminVerification2.enable();
    }//GEN-LAST:event_AddUserStartActionPerformed

    private void HelpStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpStartActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LoginContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginContinueActionPerformed
        // TODO add your handling code here:
        String outcome = Enter(InputUsername.getText(), InputPassword.getText());
        if(outcome.equals("Permitted")){
        LoginPage2.setVisible(false);
        LoginPage2.disable();
        OptionSelect3.setVisible(true);
        OptionSelect3.enable();
        }
        else{
        LoginTitle.setText("Login Failed, Please Try Again.");
        }
    }//GEN-LAST:event_LoginContinueActionPerformed

    private void AddUserContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserContinueActionPerformed
        // TODO add your handling code here:
        AddUser(InputUsername1.getText(), InputPassword1.getText());
        AddUserPage3.setVisible(false);
        AddUserPage3.disable();
        LoginPage2.setVisible(true);
        LoginPage2.enable();
    }//GEN-LAST:event_AddUserContinueActionPerformed

    private void InputUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputUsername1ActionPerformed

    private void LoginContinue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginContinue1ActionPerformed
        // TODO add your handling code here:
        if(InputUsername2.getText().equals("Admin")&&InputPassword2.getText().equals("12345")){
        AdminVerification2.setVisible(false);
        AdminVerification2.disable();
        AddUserPage3.setVisible(true);
        AddUserPage3.enable();
        }
    }//GEN-LAST:event_LoginContinue1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AddDrive4.setVisible(false);
        AddDrive4.disable();
        AddSighting5.setVisible(true);
        AddSighting5.enable();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        OptionSelect3.setVisible(false);
        OptionSelect3.disable();
        AddDrive4.setVisible(true);
        AddDrive4.enable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AnimalDropboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalDropboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnimalDropboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDrive4;
    private javax.swing.JPanel AddSighting5;
    private javax.swing.JButton AddUserContinue;
    private javax.swing.JButton AddUserHelp;
    private javax.swing.JPanel AddUserPage3;
    private javax.swing.JButton AddUserStart;
    private javax.swing.JLabel AddUserTitle;
    private javax.swing.JPanel AdminVerification2;
    private javax.swing.JComboBox<String> AnimalDropbox;
    private javax.swing.JButton HelpStart;
    private javax.swing.JPasswordField InputPassword;
    private javax.swing.JPasswordField InputPassword1;
    private javax.swing.JPasswordField InputPassword2;
    private javax.swing.JTextField InputUsername;
    private javax.swing.JTextField InputUsername1;
    private javax.swing.JTextField InputUsername2;
    private javax.swing.JButton LoginContinue;
    private javax.swing.JButton LoginContinue1;
    private javax.swing.JButton LoginHelp;
    private javax.swing.JButton LoginHelp1;
    private javax.swing.JPanel LoginPage2;
    private javax.swing.JButton LoginStart;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JLabel LoginTitle1;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel LogoStart;
    private javax.swing.JPanel OptionSelect3;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JLabel PasswordLabel2;
    private javax.swing.JPanel StartPage1;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel UsernameLabel1;
    private javax.swing.JLabel UsernameLabel2;
    private javax.swing.JLabel WelcomeTitle;
    private javax.swing.JLabel WelcomeTitle1;
    private javax.swing.JLabel WelcomeTitle2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
