/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_PANELs;

/**
 *
 * @author Michael Tomlinson
 */
public class StartPage extends javax.swing.JPanel {

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeTitle = new javax.swing.JLabel();
        WelcomeTitle1 = new javax.swing.JLabel();
        WelcomeTitle2 = new javax.swing.JLabel();
        LoginStart = new javax.swing.JButton();
        AddUserStart = new javax.swing.JButton();
        HelpStart = new javax.swing.JButton();
        LogoStart = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));
        setPreferredSize(new java.awt.Dimension(800, 450));

        WelcomeTitle.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        WelcomeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeTitle.setText("Welcome");

        WelcomeTitle1.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        WelcomeTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeTitle1.setText("to the");

        WelcomeTitle2.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        WelcomeTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeTitle2.setText("Game Drive Recording System");

        LoginStart.setBackground(new java.awt.Color(0, 255, 204));
        LoginStart.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        LoginStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Button.jpg"))); // NOI18N
        LoginStart.setText("Login");
        LoginStart.setBorder(null);
        LoginStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginStartActionPerformed(evt);
            }
        });

        AddUserStart.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        AddUserStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Button.jpg"))); // NOI18N
        AddUserStart.setText("Add User");
        AddUserStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddUserStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserStartActionPerformed(evt);
            }
        });

        HelpStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Help.jpg"))); // NOI18N
        HelpStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpStartActionPerformed(evt);
            }
        });

        LogoStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_Resources/Logo.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WelcomeTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addComponent(WelcomeTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HelpStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoStart))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(LoginStart)
                                .addGap(18, 18, 18)
                                .addComponent(AddUserStart, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(WelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(WelcomeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WelcomeTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WelcomeTitle2)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginStart, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddUserStart, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(LogoStart))
                    .addComponent(HelpStart, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoginStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginStartActionPerformed

    private void AddUserStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserStartActionPerformed

    private void HelpStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUserStart;
    private javax.swing.JButton HelpStart;
    private javax.swing.JButton LoginStart;
    private javax.swing.JLabel LogoStart;
    private javax.swing.JLabel WelcomeTitle;
    private javax.swing.JLabel WelcomeTitle1;
    private javax.swing.JLabel WelcomeTitle2;
    // End of variables declaration//GEN-END:variables
}
